# https://github.com/docker/build-push-action/issues/124
name: Push to registry, test, Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: impactful-ring-314819
  SERVICE: clothing-rater-api
  REGION: europe-west1

  REGISTRY_LOCATION: eu.gcr.io
  REGISTRY_IMAGE_NAME: eu.gcr.io/impactful-ring-314819/clothing-rater

  DATABASE_API_URL: ${{ secrets.DATABASE_API_URL }}
  SECONDS_TO_LIVE_DB_REQUEST_CACHE: 60

jobs:
  build-deploy:
    name: Build, tag, and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.CLOTHING_RATER_SA_KEY }}
          export_default_credentials: true

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Add the keys
        run: |
          mkdir -p /home/runner/.ssh
          # Replace example.com with the hostname of the machine
          # you're SSH-ing into
          ssh-keyscan github.com >> /home/runner/.ssh/known_hosts
          # DOKKU_SSH_KEY is the name of the repository secret
          echo "${{ secrets.CLOTHING_RATER_ID_RSA}}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          # ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          # ssh-add /home/runner/.ssh/github_actions

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Running unit tests (PyTest)
        run: |
          pytest --log-cli-level debug tests

      - name: Authorize Docker push
        run: gcloud auth configure-docker -q ${{ env.REGISTRY_LOCATION }}

      - name: Build Container
        run: |
          docker build \
          --build-arg ssh_prv_key="${{ secrets.CLOTHING_RATER_ID_RSA}}" \
          --build-arg ssh_pub_key="${{ secrets.CLOTHING_RATER_ID_RSA_PUB}}" \
          . \
          -t ${{ env.REGISTRY_IMAGE_NAME }}:${{ github.sha }} \
          -t ${{ env.REGISTRY_IMAGE_NAME }}:latest
      - name: Push
        run: |
          docker push ${{ env.REGISTRY_IMAGE_NAME }}:${{ github.sha }}
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --region ${{ env.REGION }} \
            --image ${{ env.REGISTRY_IMAGE_NAME }}:${{ github.sha }} \
            --platform "managed" \
            --quiet
      - name: Root traffic to latest revision
        run: |
          gcloud run services update-traffic ${{ env.SERVICE }} \
            --to-latest --platform "managed" \
            --region ${{ env.REGION }} \
            --quiet